import {Software} from "../../classes/software";
import {DiskDrive} from "../classes/disk-drive";
import {Memory} from "../classes/memory";
import {Speech} from "./speech";
import {PSG} from "./psg";
import {VDP} from "./vdp";
import {Tape} from "../classes/tape";
import {Keyboard} from "../classes/keyboard";
import {CPU} from "./cpu";
import {TMS9901} from "../classes/tms9901";
import {TIPI} from "../classes/tipi";
import {TiFdc} from "../classes/ti-fdc";
import {GenericFdc} from "../classes/generic-fdc";
import {GoogleDriveFdc} from "../classes/google-drive-fdc";

export interface Console {
    start(fast: boolean, skipBreakpoint?: boolean): void;
    reset(keepCart: boolean): void;
    frame(skipBreakpoint?: boolean): void;
    step(): void;
    stepOver(): void;
    stop(): void;
    loadSoftware(software: Software): void;
    getDiskDrives(): DiskDrive[];
    getCPU(): CPU;
    getVDP(): VDP;
    getPSG(): PSG;
    getSpeech(): Speech;
    getCRU(): TMS9901;
    getMemory(): Memory;
    getKeyboard(): Keyboard;
    getTape(): Tape;
    getDiskDrives(): DiskDrive[];
    getGenericFdc(): GenericFdc;
    getTiFdc(): TiFdc;
    getGoogleDrivesFDc(): GoogleDriveFdc;
    setGoogleDrive(): void;
    getTIPI(): TIPI | null;
    setTIPI(): void;
    setVDP(): void;
    setPSG(): void;
    isRunning(): void;
}
