import {Software} from "../../classes/software";
import {DiskDrive} from "../classes/disk-drive";
import {Memory} from "../classes/memory";
import {Speech} from "./speech";
import {PSG} from "./psg";
import {VDP} from "./vdp";
import {Tape} from "../classes/tape";
import {Keyboard} from "../classes/keyboard";
import {CPU} from "./cpu";
import {CRU} from "../classes/cru";
import {TIPI} from "../classes/tipi";
import {TiFDC} from "../classes/ti-fdc";
import {GenericFdc} from "../classes/generic-fdc";
import {GoogleDriveFDC} from "../classes/google-drive-fdc";
import {Observable} from "rxjs";
import {FDC} from "./fdc";
import {PeripheralCard} from "./peripheral-card";

export interface Console {
    start(fast: boolean, skipBreakpoint?: boolean): void;
    reset(keepCart: boolean): void;
    frame(skipBreakpoint?: boolean): void;
    step(): void;
    stepOver(): void;
    stop(): void;
    loadSoftware(software?: Software): void;
    getDiskDrives(): DiskDrive[];
    getCPU(): CPU;
    getVDP(): VDP;
    getPSG(): PSG;
    getSpeech(): Speech;
    getCRU(): CRU;
    getMemory(): Memory;
    getKeyboard(): Keyboard;
    getTape(): Tape;
    getDiskDrives(): DiskDrive[];
    getFDC(): FDC | null;
    setFDC(): void;
    getGoogleDrivesFdc(): GoogleDriveFDC;
    setGoogleDrive(): void;
    getTIPI(): TIPI | null;
    setTIPI(): void;
    setVDP(): void;
    setPSG(): void;
    isRunning(): void;
    cyclesPassed(): Observable<number>;
    getCardById(id: string): PeripheralCard | null;
}
